from typing import Any
from dataclasses import dataclass

class TOK:
    (
        und,
        op_par,
        cl_par,
        not_,
        and_,
        or_,
        mmin,
        iname,
        name,
        type,
        f,
        d,
        newer,
        newermt,
        newerct,
        arg,
        path,
        ipath,
        mtime,
        ctime,
        size,
        exec,
        conc,
        delete,
        semicolon,
        pathbind,
        grep,
        igrep,
        bgrep,
        maxdepth,
        cdup,
        first,
        abspath,
        namebind,
        nameextbind,
        trail,
        xargs,
        mdate,
        stat,
        stat2,
        async_,
        print,
        basename,
        flush,
        touch,
        cpptmp,
        docgrep,
        xlgrep,
        gitstat,
        zippath,
        zipipath,
        copy,
        flat,
        tree,
        rename,
        noover,
        image,
        video,
        move,
        extstat,
        dirwith,
        dirwithf,
        dirwithd,
        skip,
        cdin,
        pstdout,
        pstderr,
        output,
        key,
        val,
        hash,
        relpath,
        du,
        h,
        book,
        chance,
    ) = range(76)
    
def tok_type_as_string(type):
    for k, v in TOK.__dict__.items():
        if isinstance(v, int):
            if v == type:
                return k

TOK_AS_INT = {
    "(": TOK.op_par,
    ")": TOK.cl_par,
    "!": TOK.not_,
    "-not": TOK.not_,
    "-a": TOK.and_,
    "-and": TOK.and_,
    "-or": TOK.or_,
    "-mmin": TOK.mmin,
    "-iname": TOK.iname,
    "-name": TOK.name,
    "-type": TOK.type,
    "f": TOK.f,
    "d": TOK.d,
    "-newer": TOK.newer,
    "-newermt": TOK.newermt,
    "-newerct": TOK.newerct,
    "-mtime": TOK.mtime,
    "-ctime": TOK.ctime,
    "-size": TOK.size,
    "-exec": TOK.exec,
    "-async": TOK.async_,
    "-delete": TOK.delete,
    ";": TOK.semicolon,
    "\\;": TOK.semicolon,
    "{}": TOK.pathbind,
    "{path}": TOK.pathbind,
    "{name}": TOK.namebind,
    "{nameext}": TOK.nameextbind,
    "-grep": TOK.grep,
    "-igrep": TOK.igrep,
    "-bgrep": TOK.bgrep,
    "-path": TOK.path,
    "-ipath": TOK.ipath,
    "-maxdepth": TOK.maxdepth,
    "-cdup": TOK.cdup,
    "-cdin": TOK.cdin,
    "-first": TOK.first,
    "-abspath": TOK.abspath,
    "-relpath": TOK.relpath,
    "-basename": TOK.basename,
    "-conc": TOK.conc,
    "-trail": TOK.trail,
    "-xargs": TOK.xargs,
    "-mdate": TOK.mdate,
    "-stat": TOK.stat,
    "-stat2": TOK.stat2,
    "-print": TOK.print,
    "-touch": TOK.touch,
    "-flush": TOK.flush,
    "-cpptmp": TOK.cpptmp,
    "-docgrep": TOK.docgrep,
    "-xlgrep": TOK.xlgrep,
    "-gitstat": TOK.gitstat,
    "-zippath": TOK.zippath,
    "-zipipath": TOK.zipipath,
    "-copy": TOK.copy,
    "-rename": TOK.rename,
    "-flat": TOK.flat,
    "-tree": TOK.tree,
    "-noover": TOK.noover,
    "-image": TOK.image,
    "-video": TOK.video,
    "-move": TOK.move,
    "-extstat": TOK.extstat,
    "-dirwith": TOK.dirwith,
    "-dirwithf": TOK.dirwithf,
    "-dirwithd": TOK.dirwithd,
    "-skip": TOK.skip,
    "-cdin": TOK.cdin,
    "-pstdout": TOK.pstdout,
    "-pstderr": TOK.pstderr,
    "-output": TOK.output,
    "-hash": TOK.hash,
    "-du": TOK.du,
    "-h": TOK.h,
    "-book": TOK.book,
    "-chance": TOK.chance
}

TOK_AS_STR = {v:k for k,v in TOK_AS_INT.items()}

@dataclass
class T:
    type: int
    cont: str
    val: Any = None

tok_pred_noargs = [TOK.cpptmp, TOK.image, TOK.video, TOK.book]

tok_pred_nargs = [TOK.name, TOK.iname, TOK.path, TOK.ipath, TOK.mdate, 
                  TOK.xlgrep, TOK.zippath, TOK.zipipath, 
                  TOK.dirwith, TOK.dirwithf, TOK.dirwithd]

tok_pred_onearg = [TOK.mmin, TOK.type, TOK.newer, TOK.newerct, TOK.newermt, 
                   TOK.mtime, TOK.ctime, TOK.size, TOK.grep, TOK.igrep, 
                   TOK.bgrep, TOK.docgrep]

tok_pred = tok_pred_noargs + tok_pred_onearg + tok_pred_nargs